#ifndef ADAS_CLASSIFIER_REGISTERS_H
#define ADAS_CLASSIFIER_REGISTERS_H

/* design_1.hwh에서 확인한 classifier_top의 두 AXI-Lite 주소 영역. */
#define ADAS_CLASSIFIER_ARGS_BASE_ADDRESS  0x40000000u
#define ADAS_CLASSIFIER_EXEC_BASE_ADDRESS  0x40010000u
#define ADAS_CLASSIFIER_REGISTER_SPAN      0x00010000u

/* s_axi_control: DDR buffer physical address arguments. */
#define ADAS_CLASSIFIER_ARGS_IFMAP_LOW      0x10u
#define ADAS_CLASSIFIER_ARGS_IFMAP_HIGH     0x14u
#define ADAS_CLASSIFIER_ARGS_W_CONV0_LOW    0x1cu
#define ADAS_CLASSIFIER_ARGS_W_CONV0_HIGH   0x20u
#define ADAS_CLASSIFIER_ARGS_W_CONV1_LOW    0x28u
#define ADAS_CLASSIFIER_ARGS_W_CONV1_HIGH   0x2cu
#define ADAS_CLASSIFIER_ARGS_W_CONV2_LOW    0x34u
#define ADAS_CLASSIFIER_ARGS_W_CONV2_HIGH   0x38u
#define ADAS_CLASSIFIER_ARGS_OUTPUT_LOW     0x40u
#define ADAS_CLASSIFIER_ARGS_OUTPUT_HIGH    0x44u

/* s_axi_CTRL: execution control, requant and bias. */
#define ADAS_CLASSIFIER_EXEC_AP_CTRL        0x000u
#define ADAS_CLASSIFIER_EXEC_GIE            0x004u
#define ADAS_CLASSIFIER_EXEC_IER            0x008u
#define ADAS_CLASSIFIER_EXEC_ISR            0x00cu
#define ADAS_CLASSIFIER_EXEC_RQ_CONV0_LOW   0x010u
#define ADAS_CLASSIFIER_EXEC_RQ_CONV0_HIGH  0x014u
#define ADAS_CLASSIFIER_EXEC_RQ_CONV1_LOW   0x01cu
#define ADAS_CLASSIFIER_EXEC_RQ_CONV1_HIGH  0x020u
#define ADAS_CLASSIFIER_EXEC_RQ_CONV2_LOW   0x028u
#define ADAS_CLASSIFIER_EXEC_RQ_CONV2_HIGH  0x02cu
#define ADAS_CLASSIFIER_EXEC_B_CONV0_BASE   0x040u
#define ADAS_CLASSIFIER_EXEC_B_CONV1_BASE   0x080u
#define ADAS_CLASSIFIER_EXEC_B_CONV2_BASE   0x100u

#define ADAS_CLASSIFIER_AP_START_MASK       (1u << 0)
#define ADAS_CLASSIFIER_AP_DONE_MASK        (1u << 1)
#define ADAS_CLASSIFIER_AP_IDLE_MASK        (1u << 2)
#define ADAS_CLASSIFIER_AP_READY_MASK       (1u << 3)

#define ADAS_CLASSIFIER_B_CONV0_COUNT       16u
#define ADAS_CLASSIFIER_B_CONV1_COUNT       32u
#define ADAS_CLASSIFIER_B_CONV2_COUNT       64u

#endif  // ADAS_CLASSIFIER_REGISTERS_H
