#!/usr/bin/env python3
"""PL manifest 를 **소스에서 생성**한다 (손으로 쓰지 않는다).

pl_request.md 9절 요청. 학습 담당자와 PS 담당자가 같은 값을 보는 단일 정본을
만드는 것이 목적인데, 손으로 쓴 JSON 은 소스가 바뀌면 조용히 낡는다. 그래서
헤더·엔진 소스·리포트에서 직접 읽는다. 못 읽는 값은 "null" 로 두고 왜 못 읽는지
`_note` 에 적는다 — 그럴듯한 값을 채우지 않는다.

    python3 python/gen_manifest.py > forps_golden/manifest.json
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(p):
    return (ROOT / p).read_text(encoding="utf-8", errors="surrogateescape")


def define(txt, name):
    m = re.search(rf"^#define {name}\s+(\d+)", txt, re.M)
    return int(m.group(1)) if m else None


def const_u(txt, name):
    m = re.search(rf"^const unsigned {name}\s*=\s*(\d+);", txt, re.M)
    return int(m.group(1)) if m else None


ROOT_DIR = ROOT
def _one(pattern, what):
    """system/ 에서 글롭으로 **정확히 하나**를 고른다.

    2026-08-19: 여기 파일 이름이 `..._arty96_v1.rpt` 로 박혀 있었다. 이 저장소는
    트리를 복사해 세대를 올리는데(64 -> 128 -> 96), 그때 이런 이름은 안 따라온다
    (§4-j). 게다가 `rpt_row` 는 파일이 없으면 None 을 돌려주므로 manifest 에
    **면적이 조용히 null 로 들어간다** - 인계본에서 제일 안 보이는 종류다.
    0개나 2개면 세는 즉시 멈춘다.
    """
    hits = sorted(Path(ROOT_DIR).glob(pattern))
    if len(hits) != 1:
        raise SystemExit(f"[FAIL] {what}: {pattern} 이 {len(hits)}개 "
                         f"(정확히 1개여야 한다) {[str(h) for h in hits]}")
    return hits[0]


def rpt_row(path, label):
    """Vivado 리포트에서 (사용, 가용, %) 를 뽑는다."""
    try:
        txt = read(path)
    except OSError:
        return None
    m = re.search(rf"^\|\s*{re.escape(label)}\s*\*?\s*\|\s*([\d.]+)\s*\|[^|]*\|[^|]*\|\s*(\d+)\s*\|\s*([\d.]+)\s*\|",
                  txt, re.M)
    if not m:
        return None
    used = float(m.group(1))
    return {"used": int(used) if used.is_integer() else used,
            "available": int(m.group(2)), "percent": float(m.group(3))}


net = read("HW/classifier_net.h")
ce  = read("conv_engine_tr8/HW/conv_engine.h")
c0  = read("conv0_engine/HW/conv0_engine.h")
mp  = read("maxpool_engine/HW/maxpool_engine.h")

ROI  = define(net, "ROI_SIZE")
PAD0 = define(net, "CONV0_PAD")
WIRE = ROI + 2 * PAD0

# op 테이블은 헤더에서 파싱한다 - 손으로 옮기면 어긋난다.
ops = []
for m in re.finditer(r"\{\s*OP_(CONV0|CONV|MAXPOOL),\s*\"(\w+)\",\s*"
                     r"(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\s*\}", net):
    k, name, h, w, ic, oc, kk, st, pad, leaky = m.groups()
    e = {"name": name, "kind": k, "engine": {"CONV0": "conv0_engine", "CONV": "conv_engine",
                                             "MAXPOOL": "maxpool_engine"}[k],
         "input_shape": [int(h), int(w), int(ic)]}
    if k == "MAXPOOL":
        e.update(kernel=2, stride=2, padding=0,
                 output_shape=[int(h) // 2, int(w) // 2, int(oc)])
    else:
        oh = int(h) + 2 * int(pad) - int(kk) + 1
        e.update(kernel=int(kk), stride=int(st), padding=int(pad),
                 in_channels=int(ic), out_channels=int(oc),
                 activation="leaky_relu" if int(leaky) else "linear",
                 output_shape=[oh, oh, int(oc)])
        if k == "CONV0":
            e["_note"] = ("wire input is PRE-PADDED; the logical model is "
                          f"{ROI}x{ROI} with padding=1. Train with padding=1.")
    ops.append(e)

# cosim 실측 사이클
sys.path.insert(0, str(ROOT / "python"))
from collect_cosim import scan, LOGS  # noqa: E402
CYCLE_LOG = {"conv0": "conv0_cosim_x.log", "pool0": "pool_cosim_0.log",
             "conv1": "tr8_cosim_1.log",   "pool1": "pool_cosim_1.log",
             "conv2": "tr8_cosim_2.log",   "pool2": "pool_cosim_2.log"}
total = 0
for e in ops:
    cyc, verdict = scan(LOGS / CYCLE_LOG[e["name"]])
    e["cycles_measured"] = cyc if verdict == "PASS" else None
    if e["cycles_measured"]:
        total += cyc

M = {
    "schema_version": "1.0.0",
    "_source": "generated by python/gen_manifest.py - do not hand-edit",
    "board": {"name": "Arty Z7-20", "part": "xc7z020clg400-1",
              "pl_clock_mhz": 100, "tools": "Vivado 2024.2 / Vitis HLS 2024.2"},

    "input": {
        "logical_shape": [ROI, ROI, 3],
        "wire_shape": [WIRE, WIRE, 3],
        "wire_bytes": WIRE * WIRE * 3,
        "pre_pad_pixels": PAD0,
        "pre_pad_value_int8": 0,
        "layout": "NHWC",
        "dtype": "int8",
        "zero_point": 0,
        "min_alignment_bytes": 4,
        "recommended_alignment_bytes": 64,
        "_note": ("wire_shape is what conv0_engine reads. PS adds the zero border. "
                  "logical_shape/wire_shape are RUNTIME registers - a smaller ROI "
                  f"runs on this bitstream; the ceiling is MAX_IMG_W."),
    },

    "quantization": {
        "activation": {"scheme": "symmetric_per_tensor", "dtype": "int8", "zero_point": 0},
        "weight": {"scheme": "symmetric_per_tensor", "dtype": "int8", "zero_point": 0,
                   "per_output_channel_scale_supported": False},
        "bias_dtype": "int32",
        "accumulator_dtype": "int32",
        "internal_partial_bits": const_u(ce, "partial_t") or 28,
        "requant": {"multiplier": "int32 (signed)", "shift": "uint8",
                    "order": "accumulate -> bias -> leaky_relu -> multiply -> round_shift -> saturate"},
        "leaky_relu": {"numerator": 13, "denominator": 128, "value": 13 / 128,
                       "fixed_in_bitstream": True},
        "rounding": "round_half_away_from_zero: sign(x)*((abs(x)+2^(s-1))>>s)",
        "saturation": "clamp to [-128,127] AFTER the shift, evaluated in 64-bit",
        "reference_impl": ["verif_host/gen_golden.c", "python/verify_golden.py"],
        "_note": "the two reference impls agree bit-exactly on all 6 ops",
    },

    "layers": ops,

    "weight_layout": {
        "canonical": "OIHW [out_ch][in_ch][K][K] int8",
        "conv0": {"wire": "OIHW (no transpose)", "bytes": 16 * 3 * 3 * 3,
                  "_warning": ("a WPACK-transposed blob is the SAME 432 bytes and "
                               "loads without error. Special-case conv0 in the exporter.")},
        "conv1_conv2": {"wire": "[out_ch][K][K][in_ch]  (channel innermost)",
                        "numpy": "np.transpose(w, (0,2,3,1))",
                        "index": "dst[((oc*K+ky)*K+kx)*in_ch+ic] = src[((oc*in_ch+ic)*K+ky)*K+kx]"},
        "pack": {"lanes_per_word": 4, "lane0": "least significant byte = lowest channel index",
                 "endian": "little", "_note": "contiguous .tofile() already produces wire order"},
    },

    "pl_output": {"shape": [ROI // 8, ROI // 8, 64], "dtype": "int8", "layout": "NHWC",
                  "bytes": (ROI // 8) * (ROI // 8) * 64},

    "ps_tail": {
        "gap_mode": "sum",
        "gap_divisor_folded_into_fc": True,
        # 2026-08-19 신설: 나눗수를 **명시값으로** 싣는다. 지금까지는
        # `pl_output.shape` 에서 유도하라는 뜻이었는데, PS 쪽은 64 판 문서
        # (`pl_response.md`, 나눗수 64)를 같이 갖고 있을 수 있다. 해상도가
        # 바뀌면 64/144/256 으로 달라지고, 틀려도 **argmax 는 그대로 맞고
        # confidence 만 틀려서** 기능 시험을 통과한다 - 사람 눈으로 안 잡힌다.
        # 값은 체인 출력 형상에서 유도하므로 해상도를 바꾸면 따라온다.
        "gap_divisor": (ROI // 8) * (ROI // 8),
        "gap_output_dtype": "int32",
        "fc_weight": "int8 [num_classes][64], row-major",
        "fc_bias_dtype": "int32",
        "fc_accumulator_dtype": "int32",
        "logits_dtype": "int32",
        "output_scale": "reuse the conv requant form: (multiplier:int32, shift:uint8)",
        "reference_impl": "SW/classifier_run.c",
        "num_classes": None,
        "class_order": None,
        "_note": "num_classes/class_order are the training side's choice - PL never sees them",
    },

    "runtime_replaceable": {
        "conv_weights": True, "conv_bias": True,
        "requant_multiplier": True, "requant_shift": True, "leaky_relu_enable": True,
        "shape_registers": True,
        "_note": "changing any of these needs NO re-synthesis",
    },
    "fixed_in_bitstream": {
        "conv_MAX_IMG_W": const_u(ce, "MAX_IMG_W"),
        "conv_MAX_IN_CH": const_u(ce, "MAX_IN_CH"),
        "conv_MAX_OUT_CH": const_u(ce, "MAX_OUT_CH"),
        "conv_PE_OC": const_u(ce, "PE_OC"),
        "conv_TR": const_u(ce, "TR"),
        "conv0_MAX_IMG_W": const_u(c0, "MAX_IMG_W"),
        "conv0_IN_CH": const_u(c0, "IN_CH"),
        "conv0_OUT_CH": const_u(c0, "OUT_CH"),
        "conv0_K": const_u(c0, "K"),
        "maxpool_MAX_IMG_W": const_u(mp, "MAX_IMG_W"),
        "maxpool_MAX_CH": const_u(mp, "MAX_CH"),
        "conv_stride": 1,
        "leaky_slope": "13/128",
        "_note": "exceeding any of these requires re-synthesis",
    },

    "performance": {
        "source": "cosim, bit-exact, @100 MHz",
        "cycles_per_roi": total or None,
        "ms_per_roi": round(total / 1e5, 3) if total else None,
        "roi_per_second": round(1e8 / total) if total else None,
        "_excluded": ["PS GAP/FC/softmax", "Ethernet transfer",
                      "s_axilite round trips (6 kernel starts per ROI)",
                      "real DDR bandwidth (cosim uses an ideal AXI slave; "
                      "Arty DDR3 is 16-bit wide, half of Zybo)"],
    },

    "resources_implemented": {
        "source": "Vivado place & route",
        "lut": rpt_row(_one("system/utilization_impl_*.rpt", "impl utilization"), "Slice LUTs"),
        "ff": rpt_row(_one("system/utilization_impl_*.rpt", "impl utilization"), "Slice Registers"),
        "slice": rpt_row(_one("system/utilization_impl_*.rpt", "impl utilization"), "Slice"),
        "bram": rpt_row(_one("system/utilization_impl_*.rpt", "impl utilization"), "Block RAM Tile"),
        "dsp": rpt_row(_one("system/utilization_impl_*.rpt", "impl utilization"), "DSPs"),
        "wns_ns": None,
        "_note": "wns is parsed separately; see system/timing_impl_*.rpt",
    },
}

# WNS
try:
    t = read(_one("system/timing_impl_*.rpt", "impl timing"))
    blk = t.split("Design Timing Summary", 1)[1]
    m = re.search(r"^\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s+(\d+)", blk, re.M)
    if m:
        M["resources_implemented"]["wns_ns"] = float(m.group(1))
        M["resources_implemented"]["failing_endpoints"] = int(m.group(3))
except (OSError, IndexError):
    pass

json.dump(M, sys.stdout, indent=2, ensure_ascii=False)
print()
