// ===========================================================================
// conv_engine_tb.cpp - ARTY CLASSIFIER FORK (2026-08-18)
//
// Forked from hls/zybo_conv_engine_tr16/HW/conv_engine_tb.cpp. Delta:
//   - real_layers_data.h (64 MB) and the whole real-layer suite are DROPPED.
//     That data is YOLOv3-tiny-ADAS; this build runs the ROI classifier and
//     its weights do not exist yet (the model is not trained).
//   - main() replaced: runs the three classifier conv shapes from
//     ../../HW/classifier_net.h instead of the 8 synthetic configs + 13 real
//     layers.
//
// Everything above main() - pack4 helpers, reference_conv(), run_config() -
// is verbatim from the fork source and its comments still apply.
//
// What this proves and what it does not:
//   PROVES  : conv_engine() is bit-exact against an independent reference
//             convolution on the exact shapes the classifier will run, and
//             (under cosim) how many CYCLES each of those shapes costs.
//   DOES NOT: say anything about classification accuracy. Weights here are
//             pseudo-random. Cycle counts do not depend on weight VALUES, so
//             the timing result is real even though the model is not trained.
// ===========================================================================
#include <algorithm>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include "conv_engine.h"
// Real per-layer data (REAL_WEIGHTS_PLAN.md step 7) - generated by
// python/real_layers.py, NOT hand-written. See run_real_layer() below and
// this header's own top comment for why it's embedded rather than read
// from python/layerNN_*.bin at C-sim runtime.

// Full m_axi interface depths - must match conv_engine.cpp's `#pragma HLS
// INTERFACE m_axi ... depth=...` expressions exactly. C/RTL co-simulation
// builds its RTL bus-functional-model's memory image from the host pointer
// using this depth, regardless of how much of it a given call's actual
// img_h/img_w/in_ch/out_ch/k dimensions use - passing a host array smaller
// than `depth` makes cosim read past the end of the allocation (SIGSEGV
// during ENTER_WRAPC; see TROUBLESHOOTING.md's cosim entry). Plain C-sim
// never uses `depth` at all, so this was never needed until cosim was
// attempted.
// ifmap/weights depths now scale with MAX_TOTAL_IN_CH (1024), not MAX_IN_CH
// (128) - see conv_engine.cpp's matching m_axi depth= pragmas for why
// (input-channel tiling: on-chip buffers stay MAX_IN_CH-wide, but the DDR
// arrays they're tiled slices of must be addressable across a layer's real
// total in_ch).
static const size_t IFMAP_DEPTH   = (size_t)MAX_IMG_W * MAX_IMG_W * MAX_TOTAL_IN_CH;

// ---- PACK4 testbench helpers ----------------------------------------------
// conv_engine's `ifmap` port is now pack4_t (4 consecutive NHWC channels per
// 32-bit beat, see HW/pack4.h), so the tb's ifmap buffer is allocated and
// passed in WORDS. Every other port is unchanged.
//
// The reference_conv() model and all the golden arrays stay entirely
// int8_t-based and completely unaware of the packing - that is what makes a
// PASS here evidence the packing is bit-exact, rather than evidence that
// both sides share the same packing bug.
//
// IFMAP_DEPTH above stays in ELEMENTS so it still reads as the same
// img/ch bound product the engine's depth= pragma uses; pack4_words()
// converts at each point of use.
static inline size_t pack4_words(size_t elems) {
    return (elems + PACK4_LANES - 1) / PACK4_LANES;
}

// Flat int8 element index -> (word, lane), matching pack4.h's little-endian
// lane order: lane 0 is the lowest channel index and the low byte. This is
// the mapping the DDR byte layout already had, which is why no PS-side
// repacking is needed in real hardware - it is spelled out here only
// because the tb holds its golden data in a separate int8_t array.
static inline void pack4_put(std::vector<pack4_t> &buf, size_t elem_idx, int8_t v) {
    pack4_set(buf[elem_idx / PACK4_LANES], (unsigned)(elem_idx % PACK4_LANES), (ap_int<8>)v);
}
// WPACK: weights move from OIHW ([oc][ic][ky][kx], ic stride k*k) to
// [oc][ky][kx][ic] (ic stride 1, innermost) so that one 4-byte AXI beat
// carries FOUR DIFFERENT ic. That is the whole point: `wtile_packed` is
// already ARRAY_PARTITION cyclic factor=TR on its ic dimension, so 4
// different ic land in 4 different banks and the existing partitioning
// absorbs the write with no change. Packing along the old innermost axis
// (kx) instead would put 4 values of the SAME ic in one beat, which
// collides on that bank and would need ky/kx partitioned complete -
// 256 -> 2304 banks, i.e. BRAM blowup. See the plan doc's
// "[design decision] option (A), keeping the layout unchanged, dies on resources".
//
// This runs host-side because on real hardware it is the PS that writes the
// weight buffer into DDR; the layout is a SW contract, not a golden-data
static void repack_weights_okkxi(std::vector<pack4_t> &dst, const int8_t *src,
                                 unsigned out_ch, unsigned in_ch, unsigned k) {
    for (unsigned oc = 0; oc < out_ch; oc++)
        for (unsigned ic = 0; ic < in_ch; ic++)
            for (unsigned ky = 0; ky < k; ky++)
                for (unsigned kx = 0; kx < k; kx++) {
                    size_t s = ((size_t)(oc * in_ch + ic) * k + ky) * k + kx;
                    size_t d = ((size_t)(oc * k + ky) * k + kx) * in_ch + ic;
                    pack4_put(dst, d, src[s]);
                }
}

static const size_t WEIGHTS_DEPTH = (size_t)MAX_OUT_CH * MAX_TOTAL_IN_CH * MAX_K * MAX_K;
static const size_t BIAS_DEPTH    = (size_t)MAX_OUT_CH;
static const size_t OFMAP_DEPTH   = (size_t)MAX_IMG_W * MAX_IMG_W * MAX_OUT_CH;
// ACCUM_DEPTH disappeared on 2026-08-08: when accum moved on-chip (URAM) it
// dropped out of conv_engine()'s argument list, so the TB no longer has to
// allocate that buffer at all. Sizing is now decided solely by ACCUM_POSITIONS
// inside the kernel, and its bound is enforced by the assert in conv_engine()
// (see the ACCUM_POSITIONS comment in conv_engine.h).

// ---------------------------------------------------------------------------
// C-simulation testbench for conv_engine.
//
// Unlike conv_layer1_tb.cpp (which drives ONE fixed, compile-time-sized
// layer), this testbench exists specifically to prove the engine's core
// claim: that it produces correct output across DIFFERENT runtime
// geometries, not just the one shape it happens to be compiled for. It runs
// eleven deliberately different configs (A-K, see main() below) through the
// same conv_engine() call, each exercising a different edge case (multi-tile
// output-channel tiling, k=1, minimal channel counts, the MAX_IN_CH boundary,
// a non-multiple-of-TR reduction, non-square images, a pe-pair straddling
// the out_ch boundary after a preceding full tile (config H, added for this
// project's INT8 DSP-packing experiment), and - configs I/J/K, added once
// the real network showed input-channel tiling was needed, see
// conv_engine.h - multi-pass ic_tile coverage with and without a remainder,
// and both oc_tile/ic_tile tiling happening at once), plus one dedicated
// "config-A-cosim" repeat of config-A sized for C/RTL
// co-simulation specifically (see run_config()'s pad_to_full_depth
// parameter). Before the config sweep, main() also runs
// pack_unpack_selftest_fast() (exhaustive, plain-int) and
// pack_unpack_selftest_ap_int_sample() (a smaller ap_int-typed confirmation
// pass) - see the comment above their definitions for why it's split into
// two rather than one.
//
// Sizes are intentionally small (not the real 416x416 Phase 1 input) - this
// suite is about proving runtime-parameterization correctness quickly, not
// about exercising the real network's actual layer sizes. The real sizes
// only matter once this passes and the design moves to hardware bring-up
// (SW/network_run.c) on actual silicon, per doc/05_learning/hls-study-plan.md's phased
// approach. Only "config-A-cosim" pays the cost of full-m_axi-depth host
// buffers (IFMAP_DEPTH etc. below) - the other 8 configs stay at their
// actual, small per-config sizes, since plain C-sim never reads `depth` at
// all and paying that cost on every config (tried first) made ordinary
// C-sim dramatically slower for no benefit to it.
// ---------------------------------------------------------------------------

static int8_t clamp_i8(int64_t v) {
    if (v > 127)  return 127;
    if (v < -128) return -128;
    return (int8_t)v;
}

// round(x / 2^s), ties away from zero - plain int64_t implementation of the
// same RTL_HANDOFF_KO.md section 5 formula conv_engine.cpp's round_shift()
// implements in ap_int<64>. Written independently here (not calling into
// conv_engine.cpp, whose round_shift()/apply_activation() are file-local
// static functions anyway) so a bug in one has no way to silently agree
// with the other - same "no shared code path" reasoning this function's
// caller already documents for the conv math itself.
static int64_t round_shift_ref(int64_t x, unsigned s) {
    if (s == 0) return x;
    int64_t half = (int64_t)1 << (s - 1);
    return (x >= 0) ? ((x + half) >> s) : -(((-x) + half) >> s);
}

// Independent reference convolution - deliberately NOT sharing any code path
// with conv_engine.cpp (no shared window/line-buffer structure), so a bug in
// conv_engine's raster-scan indexing has no way to silently agree with this.
static void reference_conv(
    const std::vector<int8_t> &x, const std::vector<int8_t> &w, const std::vector<int32_t> &b,
    std::vector<int8_t> &out,
    unsigned img_h, unsigned img_w, unsigned in_ch, unsigned out_ch,
    unsigned k, unsigned pad,
    bool leaky_relu_enable, int32_t requant_multiplier, unsigned requant_shift
) {
    unsigned out_h = img_h + 2 * pad - k + 1;
    unsigned out_w = img_w + 2 * pad - k + 1;
    out.assign((size_t)out_h * out_w * out_ch, 0);

    for (unsigned r = 0; r < out_h; r++) {
        for (unsigned c = 0; c < out_w; c++) {
            for (unsigned oc = 0; oc < out_ch; oc++) {
                int64_t acc = b[oc];
                for (unsigned ic = 0; ic < in_ch; ic++) {
                    for (unsigned ky = 0; ky < k; ky++) {
                        for (unsigned kx = 0; kx < k; kx++) {
                            int in_r = (int)r + (int)ky - (int)pad;
                            int in_c = (int)c + (int)kx - (int)pad;
                            int8_t px = 0;
                            if (in_r >= 0 && in_r < (int)img_h &&
                                in_c >= 0 && in_c < (int)img_w) {
                                px = x[((size_t)in_r * img_w + in_c) * in_ch + ic];
                            }
                            unsigned w_idx = ((oc * in_ch + ic) * k + ky) * k + kx;
                            acc += (int64_t)px * (int64_t)w[w_idx];
                        }
                    }
                }
                // RTL_HANDOFF_KO.md section 5, in order: LeakyReLU(13/128) on
                // the raw accumulator (only if negative), THEN per-layer
                // requantize, THEN saturate - NOT the old placeholder
                // "acc>=0 ? acc : acc>>3" this replaces.
                if (leaky_relu_enable && acc < 0) {
                    acc = round_shift_ref(acc * 13, 7);
                }
                int64_t scaled = acc * (int64_t)requant_multiplier;
                int64_t activated = round_shift_ref(scaled, requant_shift);
                out[((size_t)r * out_w + c) * out_ch + oc] = clamp_i8(activated);
            }
        }
    }
}

// Self-test of the INT8 DSP-packing primitive (conv_engine.h's
// packed_weight_t, and the pack/unpack math in conv_engine.cpp's
// load_weight_tile()/scan_and_compute()), run in isolation before the
// config sweep below. RESOURCE_BUDGET.md §5 flags this exact technique as
// "getting it wrong silently produces wrong math rather than a synthesis
// error" - split into two passes rather than one, for a reason found the
// hard way (see below).
//
// Pass 1 (pack_unpack_selftest_fast): exhaustively brute-forces ALL
// 256*256*256 = 16,777,216 (X, Y_lo, Y_hi) triples, but using PLAIN native
// integer arithmetic that emulates the exact same mask/shift/sign-extend
// operations, not real ap_int types. This is what actually matters for
// correctness - it's what caught the original missing "+1 carry when the
// low field's sign bit is set" bug, which was a math error, not an
// ap_int-specific one. It runs in well under a second.
//
// Pass 2 (pack_unpack_selftest_ap_int_sample): confirms the REAL ap_int/HLS
// types (packed_weight_t, .range(), signed shifts, casts) behave exactly
// like pass 1's plain-int model - but only over a much smaller, deliberately
// chosen set (all sign/magnitude corner cases + a fixed reproducible random
// sample), not the full 16.7M. Running the full exhaustive sweep through
// real ap_int arithmetic was tried first and made C-sim impractically
// slow (looked "stuck") - ap_int's arbitrary-precision simulation model
// pays real per-operation overhead that a native int does not, and at
// 16.7M iterations that overhead compounds into minutes-to-hours instead
// of seconds. This pass exists only to catch an ap_int-semantics surprise
// (e.g. if `.range()`'s sign-reinterpretation behaved differently than
// assumed) that pass 1 - being plain-int - could not catch on its own.
//
// Both are pure C++ host-side tests - never synthesized, no __SYNTHESIS__
// guard needed.
static void pack_unpack_selftest_fast() {
    for (int xi = -128; xi <= 127; xi++) {
        for (int yhi = -128; yhi <= 127; yhi++) {
            for (int ylo = -128; ylo <= 127; ylo++) {
                uint32_t y_lo_biased = (uint8_t)ylo ^ 0x80u;
                int64_t packed = ((int64_t)yhi << 16) | y_lo_biased;
                int64_t product = (int64_t)xi * packed;

                int32_t low16 = (int32_t)(product & 0xFFFF);
                if (low16 & 0x8000) low16 -= 0x10000; // sign-extend, matches ap_int<16>

                int64_t contrib_hi = product >> 16; // matches ap_int's arithmetic shift
                if (low16 < 0) contrib_hi += 1;      // the carry correction under test
                int64_t contrib_lo = low16 - ((int64_t)xi << 7);

                if (contrib_hi != (int64_t)xi * yhi || contrib_lo != (int64_t)xi * ylo) {
                    printf("pack_unpack_selftest_fast FAIL: x=%d y_lo=%d y_hi=%d "
                           "-> contrib_lo=%lld (want %d) contrib_hi=%lld (want %d)\n",
                           xi, ylo, yhi, (long long)contrib_lo, xi * ylo,
                           (long long)contrib_hi, xi * yhi);
                    assert(false && "packed MAC split algorithm mismatch");
                }
            }
        }
    }
    printf("pack_unpack_selftest_fast: 16,777,216 combinations (plain-int model) PASS\n");
}

static void pack_unpack_selftest_ap_int_sample() {
    auto check_one = [](int xi, int ylo, int yhi) {
        act_t x = (act_t)xi;
        weight_t y_hi = (weight_t)yhi;
        weight_t y_lo = (weight_t)ylo;

        // Mirrors load_weight_tile()'s pack step exactly.
        ap_uint<8> y_lo_biased = (ap_uint<8>)y_lo ^ (ap_uint<8>)0x80;
        packed_weight_t packed =
            (((ap_int<25>)y_hi) << 16) + (ap_int<25>)y_lo_biased;

        // Mirrors scan_and_compute()'s MAC_KX unpack step exactly, including
        // the +1 carry correction on contrib_hi.
        ap_int<33> product = x * packed;
        ap_int<16> l_signed = product.range(15, 0);
        accum_t contrib_hi = (accum_t)(product >> 16);
        if (l_signed < 0) {
            contrib_hi += 1;
        }
        accum_t contrib_lo = (accum_t)l_signed - ((accum_t)x << 7);

        if (contrib_hi != xi * yhi || contrib_lo != xi * ylo) {
            printf("pack_unpack_selftest_ap_int_sample FAIL: x=%d y_lo=%d y_hi=%d "
                   "-> contrib_lo=%d (want %d) contrib_hi=%d (want %d)\n",
                   xi, ylo, yhi, (int)contrib_lo, xi * ylo,
                   (int)contrib_hi, xi * yhi);
            assert(false && "packed MAC split ap_int-type mismatch");
        }
    };

    // All sign/magnitude corner cases: 6*6*6 = 216 combinations, covering
    // every boundary the split logic's correctness actually depends on
    // (most negative, most positive, +-1, zero).
    const int corners[] = {-128, -127, -1, 0, 1, 127};
    for (int xi : corners)
        for (int yhi : corners)
            for (int ylo : corners)
                check_one(xi, ylo, yhi);

    // Fixed, reproducible pseudo-random sample across the full range, to
    // catch anything the hand-picked corners above might miss - small
    // enough to stay fast even at ap_int's simulation speed.
    srand(12345);
    for (int i = 0; i < 20000; i++) {
        int xi  = (rand() % 256) - 128;
        int ylo = (rand() % 256) - 128;
        int yhi = (rand() % 256) - 128;
        check_one(xi, ylo, yhi);
    }

    printf("pack_unpack_selftest_ap_int_sample: 216 corner + 20,000 random "
           "combinations (real ap_int types) PASS\n");
}

// Runs one config through conv_engine() and checks it against reference_conv().
// Returns 0 on PASS, 1 on FAIL (mirrors conv_layer1_tb.cpp's convention).
//
// `pad_to_full_depth` (default false): when true, allocates the four
// host-side arrays passed to conv_engine() at the FULL m_axi depth
// (IFMAP_DEPTH etc. above) instead of this config's actual (much smaller)
// dimensions - only actually needed for C/RTL co-simulation (see the
// comment on those constants). Defaults to false because plain C-sim
// never reads `depth` at all, and unconditionally paying for ~200M-element
// allocations across all 8 configs (tried first) made ordinary C-sim
// dramatically slower - the same category of problem as the exhaustive
// ap_int self-test's slowdown (TROUBLESHOOTING.md §7), just ~100x more
// ap_int-construction work (1.6 billion elements across 8 configs vs. that
// entry's 16.7 million). Only the one dedicated cosim config in main()
// passes true - cosim's job is checking the tool's C-to-RTL translation
// fidelity on a representative case, not re-proving algorithm correctness
// across edge cases, which the other 8 configs already do exhaustively via
// fast, small-buffer C-sim.
static int run_config(
    const char *name,
    unsigned img_h, unsigned img_w, unsigned in_ch, unsigned out_ch,
    unsigned k, unsigned pad, unsigned seed,
    bool leaky_relu_enable, int32_t requant_multiplier, unsigned requant_shift,
    bool pad_to_full_depth = false,
    // 2026-08-19: 0 보다 크면 **이 형상이 실제로 포화를 밟는지** 검사한다.
    // 포화 커버리지 형상을 추가해 놓고 파라미터가 바뀌어 더 이상 포화를
    // 안 밟게 되면, PASS 는 계속 나오면서 커버리지만 조용히 사라진다.
    // 그것이 이 저장소에서 가장 비싼 실패 유형이라 숫자로 못박는다.
    double min_sat_pct = 0.0, double max_sat_pct = 100.0
) {
    srand(seed);

    std::vector<int8_t>  x((size_t)img_h * img_w * in_ch);
    std::vector<int8_t>  w((size_t)out_ch * in_ch * k * k);
    std::vector<int32_t> b(out_ch);

    for (auto &v : x) v = (int8_t)((rand() % 41) - 20);
    for (auto &v : w) v = (int8_t)((rand() % 11) - 5);
    // Wider range than weight_t's [-5,4] above - bias is now signed INT32
    // (bias_t, matching the golden model's bias.bin), so this exercises
    // values a plain INT8 bias never could.
    for (auto &v : b) v = (int32_t)((rand() % 2001) - 1000);

    std::vector<int8_t> ref_out;
    reference_conv(x, w, b, ref_out, img_h, img_w, in_ch, out_ch, k, pad,
                   leaky_relu_enable, requant_multiplier, requant_shift);

    unsigned out_h = img_h + 2 * pad - k + 1;
    unsigned out_w = img_w + 2 * pad - k + 1;

    size_t ifmap_size   = pad_to_full_depth ? IFMAP_DEPTH   : x.size();
    size_t weights_size = pad_to_full_depth ? WEIGHTS_DEPTH : w.size();
    size_t bias_size    = pad_to_full_depth ? BIAS_DEPTH    : b.size();
    size_t ofmap_size   = pad_to_full_depth ? OFMAP_DEPTH   : (size_t)out_h * out_w * out_ch;

    // Only the front sub-region (this config's real data) is filled when
    // pad_to_full_depth is set; the rest stays zero-padding that
    // conv_engine() never reads or writes, since its own loop bounds come
    // from img_h/img_w/in_ch/out_ch/k, not from how large the underlying
    // buffer happens to be.
    // PACK4: only the ifmap buffer is word-allocated - every other port
    // keeps its original element type. See pack4_words()/pack4_put() below.
    std::vector<pack4_t> x_hw(pack4_words(ifmap_size), (pack4_t)0);
    // WPACK: weights are word-allocated now too (repack_weights_okkxi).
    std::vector<pack4_t> w_hw(pack4_words(weights_size), (pack4_t)0);
    std::vector<bias_t> b_hw(bias_size, (bias_t)0);
    std::vector<act_t> hw_out(ofmap_size, (act_t)0);

    for (size_t i = 0; i < x.size(); i++) pack4_put(x_hw, i, x[i]);
    repack_weights_okkxi(w_hw, w.data(), out_ch, in_ch, k);
    std::copy(b.begin(), b.end(), b_hw.begin());

    // w_hw.data() passed twice - weights_hi is a second, independent m_axi
    // port aliasing the SAME weight data (see conv_engine.h's note on this
    // param), not a separate buffer. In real hardware, software programs
    // both address registers with the same DRAM base address; here in C-sim
    // the equivalent is simply reusing the same host-side vector.
    conv_engine(
        x_hw.data(), w_hw.data(), w_hw.data(), b_hw.data(), hw_out.data(),
        (uint16_t)img_h, (uint16_t)img_w, (uint16_t)in_ch, (uint16_t)out_ch,
        (uint8_t)k, /*stride=*/1, (uint8_t)pad,
        requant_multiplier, (uint8_t)requant_shift, (uint8_t)(leaky_relu_enable ? 1 : 0)
    );

    unsigned mismatches = 0;
    unsigned total = out_h * out_w * out_ch;
    for (unsigned i = 0; i < total; i++) {
        int8_t hw_val = (int8_t)hw_out[i];
        int8_t ref_val = ref_out[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%u: hw=%d ref=%d\n",
                       name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        unsigned sat = 0;
        for (unsigned i = 0; i < total; i++)
            if (ref_out[i] == 127 || ref_out[i] == -128) sat++;
        double sat_pct = total ? 100.0 * (double)sat / (double)total : 0.0;
        printf("[%s] PASS: %u output values matched the reference bit-exactly "
               "(img %ux%ux%u -> %ux%ux%u, k=%u, pad=%u) [포화 %.1f%%]\n",
               name, total, img_w, img_h, in_ch, out_w, out_h, out_ch, k, pad,
               sat_pct);
        if (min_sat_pct > 0.0 && (sat_pct < min_sat_pct || sat_pct > max_sat_pct)) {
            printf("  [%s] FAIL: 포화 커버리지 %.1f%% 가 요구 구간 "
                   "[%.1f%%, %.1f%%] 밖이다 - 이 형상은 더 이상 포화 경로를 "
                   "시험하지 않는다\n", name, sat_pct, min_sat_pct, max_sat_pct);
            return 1;
        }
        return 0;
    } else {
        printf("[%s] FAIL: %u/%u values mismatched\n", name, mismatches, total);
        return 1;
    }
}


// ---------------------------------------------------------------------------
// Classifier conv shapes. Kept in sync BY HAND with ../../HW/classifier_net.h
// (that header is C, not C++-includable here without pulling the op struct in
// - if you change one, change both; check_shapes.py in ../../python asserts
// they still agree).
// ---------------------------------------------------------------------------
struct ClsConv {
    const char *name;
    unsigned img_h, img_w, in_ch, out_ch, k, pad;
};

static const ClsConv CLS_CONVS[] = {
    { "conv0 (3->16 @96x96)",    96,  96,  3, 16, 3, 1 },
    { "conv1 (16->32 @48x48)",   48,  48, 16, 32, 3, 1 },
    { "conv2 (32->64 @24x24)",   24,  24, 32, 64, 3, 1 },
    // [3] D1 진단용 (2026-08-18): conv1 과 형상이 같고 out_ch 만 절반이라
    // oc_tile 이 2개 -> 1개가 된다. cosim 사이클을 conv1 에서 빼면 **oc_tile
    // 한 개의 한계비용**이 나오고, 그 안의 반복 수는 알고 있으므로
    // 고정비(fill+호출)를 추정이 아니라 실측으로 분리할 수 있다.
    // 인덱스 0~2 는 건드리지 말 것 - check_shapes.py §3 이 순서를 대조한다.
    { "D1 conv1 half-oc (16->16 @48x48)", 48, 48, 16, 16, 3, 1 },
};
static const unsigned NUM_CLS_CONVS = sizeof(CLS_CONVS) / sizeof(CLS_CONVS[0]);

int main(int argc, char **argv) {
    // Same argv protocol as the fork source: cosim_design -argv passes
    // --cosim-only so that exactly ONE conv_engine() call happens, and it is
    // one sized with pad_to_full_depth=true (cosim's bus-functional model is
    // sized from the m_axi depth= pragma, so a short host buffer SIGSEGVs in
    // ENTER_WRAPC). Optional second argv picks WHICH classifier conv to
    // simulate - that is how per-op cycle counts get measured.
    bool cosim_only = (argc > 1 && std::strcmp(argv[1], "--cosim-only") == 0);
    int cosim_op = -1;
    if (cosim_only && argc > 2) {
        cosim_op = std::atoi(argv[2]);
        if (cosim_op < 0 || cosim_op >= (int)NUM_CLS_CONVS) {
            printf("--cosim-only: op index %d out of range [0,%u), using 0\n",
                   cosim_op, NUM_CLS_CONVS);
            cosim_op = 0;
        }
    }
    if (cosim_only && cosim_op < 0) cosim_op = 0;

    pack_unpack_selftest_fast();
    pack_unpack_selftest_ap_int_sample();

    // Requantization pair from the YOLOv3-tiny-ADAS golden model's layer 0
    // (python_teammate/darknet_golden/.../model_manifest.json). Used as a
    // stand-in until the classifier is trained and has its own per-layer
    // scales: the point is to exercise the requantize path with a value of
    // realistic magnitude rather than an easy round number. It does not need
    // to be the classifier's eventual scale for the cycle count to be valid.
    const int32_t STANDIN_MULTIPLIER = 1264723901;
    const unsigned STANDIN_SHIFT = 37;

    int fail = 0;

    if (cosim_only) {
        const ClsConv &c = CLS_CONVS[cosim_op];
        printf("=== COSIM op %d: %s ===\n", cosim_op, c.name);
        fail = run_config(c.name, c.img_h, c.img_w, c.in_ch, c.out_ch,
                          c.k, c.pad, /*seed=*/42,
                          /*leaky_relu_enable=*/true,
                          STANDIN_MULTIPLIER, STANDIN_SHIFT,
                          /*pad_to_full_depth=*/true);
        printf(fail ? "COSIM CONFIG FAILED\n" : "COSIM CONFIG PASS\n");
        return fail ? 1 : 0;
    }

    // C-sim: all three shapes, plus a k=1 case. k=1 is not in the baseline
    // architecture but the engine supports it and a 1x1 bottleneck is the
    // most likely thing the training side adds, so it is covered here rather
    // than discovered broken later.
    unsigned ran = 0;   // 손으로 센 상수(`NUM_CLS_CONVS + 2`)를 쓰면
                        // 형상을 추가할 때 이 숫자만 안 따라온다.
    for (unsigned i = 0; i < NUM_CLS_CONVS; i++) {
        const ClsConv &c = CLS_CONVS[i];
        ran++;
        fail |= run_config(c.name, c.img_h, c.img_w, c.in_ch, c.out_ch,
                           c.k, c.pad, /*seed=*/42 + i,
                           /*leaky_relu_enable=*/true,
                           STANDIN_MULTIPLIER, STANDIN_SHIFT);
    }
    ran++;
    fail |= run_config("extra: k=1 bottleneck 64->32 @16x16",
                       16, 16, 64, 32, /*k=*/1, /*pad=*/0, /*seed=*/7,
                       /*leaky_relu_enable=*/true,
                       STANDIN_MULTIPLIER, STANDIN_SHIFT);
    // leaky disabled - the classifier's last conv may feed GAP linearly.
    ran++;
    fail |= run_config("extra: leaky off 32->64 @32x32",
                       32, 32, 32, 64, 3, 1, /*seed=*/11,
                       /*leaky_relu_enable=*/false,
                       STANDIN_MULTIPLIER, STANDIN_SHIFT);

    // SATURATION COVERAGE (2026-08-19). Measured gap, not a hunch: the golden
    // this suite produces spans only ~15-19 distinct int8 values (roughly
    // -8..16) and hits +127/-128 **0.0% of the time**. Every optimisation
    // adopted on 2026-08-18/19 (W4/W6/W7) was justified by "csim bit-exact",
    // so a change that broke the saturate step would have passed unnoticed.
    // Real trained weights will saturate; the stand-in ones do not.
    //
    // A much smaller shift raises the requant gain so the accumulator lands
    // outside int8 for a large fraction of positions, exercising BOTH clamps
    // in apply_activation() and in the reference model. Keep the shift low
    // enough to saturate but not so low that everything clips (all-127 would
    // be just as blind as all-0).
    ran++;
    fail |= run_config("extra: saturation sweep 16->32 @32x32 (low shift)",
                       32, 32, 16, 32, 3, 1, /*seed=*/23,
                       /*leaky_relu_enable=*/true,
                       STANDIN_MULTIPLIER, /*requant_shift=*/33,
                       /*pad_to_full_depth=*/false,
                       /*min_sat_pct=*/2.0, /*max_sat_pct=*/90.0);

    if (fail) {
        printf("CLASSIFIER CONV SUITE FAILED\n");
        return 1;
    }
    printf("CLASSIFIER CONV SUITE PASS (%u shapes)\n", ran);
    return 0;
}
